# Generated by Django 4.2 on 2023-07-25 01:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def compute_search_vector(apps, schema_editor):
    Question = apps.get_model("AskHeroes", "Question")
    Question.objects.update(
        search_vector=django.contrib.postgres.search.SearchVector("title", "content")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("AskHeroes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="question",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="AskHeroes_q_search__368f19_gin"
            ),
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
